# site_config_filled.py
#
# Auto-generated by gather_site_data.py — do not edit by hand.
# Copy the factory functions below into site_config.py to replace placeholders.
#
# Tidal data:  NOAA CO-OPS datums + harmonic constituents
# Met data:    ERA5-Land sinusoidal seasonal fit
#
# Generated: 2026-05-06 10:55 UTC

from __future__ import annotations
from dataclasses import dataclass, field

# Import dataclasses from the original config so this file is self-contained
from site_config import TideRecord, MetForcingParams, PlotConfig


# ────────────────────────────────────────────────────────
# Plum Island Estuary, MA
# CO-OPS station: 8419870
# ────────────────────────────────────────────────────────

def pie_default_tides() -> TideRecord:
    """
    Plum Island Estuary, MA
    Tidal data from NOAA CO-OPS station 8419870 (datums and harmonics).
    Datum reference: MSL = 0.0 m; all heights relative to MSL.
    """
    t = TideRecord()
    t.mean_sea_level_m            = 0.0
    t.mean_high_tide_m            = 1.224
    t.tidal_amplitude_m           = 1.243
    t.tidal_period_hours          = 12.42
    t.M2_amplitude_m              = 1.214
    t.M2_phase_deg                = 110.9
    t.S2_amplitude_m              = 0.177
    t.S2_phase_deg                = 147.2
    t.N2_amplitude_m              = 0.278
    t.N2_phase_deg                = 81.3
    t.K1_amplitude_m              = 0.132
    t.K1_phase_deg                = 207.0
    t.O1_amplitude_m              = 0.106
    t.O1_phase_deg                = 189.1
    t.creek_salinity_ppt          = 22.0
    t.suspended_sediment_concentration_kg_m3 = 0.020  # PLACEHOLDER
    t.fine_sediment_concentration_kg_m3      = 0.005  # PLACEHOLDER
    return t

def pie_default_met() -> MetForcingParams:
    """
    Plum Island Estuary, MA
    Seasonal parameters fitted from ERA5-Land (1985–2024).
    """
    m = MetForcingParams()
    m.temperature_mean_c          = 9.91
    m.temperature_amplitude_c     = 12.0
    m.temperature_peak_day        = 208.9
    m.par_mean_umol_m2_d          = 29073008.0
    m.par_amplitude_umol_m2_d     = 16267152.0
    m.par_peak_day                = 169.5
    m.precipitation_mean_mm_d     = 3.0   # PLACEHOLDER — add ERA5 tp variable
    m.freshwater_input_mm_d       = 0.0
    return m


